version: "3.9"
services:
  influxdb:
    image: influxdb:2
    container_name: solnova-influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=solnova
      - DOCKER_INFLUXDB_INIT_BUCKET=solnova
      - DOCKER_INFLUXDB_INIT_RETENTION=0
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: solnova-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped

volumes:
  influxdb-data:
