name: solnova_mobile
description: SOLNOVA prototype mobile app
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
