// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1mQu2Og2s3CRaHZyMTRcFsmeGS0NfqTA',
    appId: '1:89419282463:web:658cd7a50870a682dcbd2a',
    messagingSenderId: '89419282463',
    projectId: 'solnova-50d0e',
    authDomain: 'solnova-50d0e.firebaseapp.com',
    storageBucket: 'solnova-50d0e.firebasestorage.app',
    measurementId: 'G-2RNMF2L5N6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWE6cb-hAG4E9dUJ0PiIZeg_q65htPnLg',
    appId: '1:89419282463:android:eaf6ec44aa1234d5dcbd2a',
    messagingSenderId: '89419282463',
    projectId: 'solnova-50d0e',
    storageBucket: 'solnova-50d0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAltnA6P_XMzjY7SsnYtrjR3nZqUSYMdKc',
    appId: '1:89419282463:ios:b52728fe70144e37dcbd2a',
    messagingSenderId: '89419282463',
    projectId: 'solnova-50d0e',
    storageBucket: 'solnova-50d0e.firebasestorage.app',
    iosBundleId: 'com.example.solnovaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAltnA6P_XMzjY7SsnYtrjR3nZqUSYMdKc',
    appId: '1:89419282463:ios:b52728fe70144e37dcbd2a',
    messagingSenderId: '89419282463',
    projectId: 'solnova-50d0e',
    storageBucket: 'solnova-50d0e.firebasestorage.app',
    iosBundleId: 'com.example.solnovaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1mQu2Og2s3CRaHZyMTRcFsmeGS0NfqTA',
    appId: '1:89419282463:web:d10aea05458b52e1dcbd2a',
    messagingSenderId: '89419282463',
    projectId: 'solnova-50d0e',
    authDomain: 'solnova-50d0e.firebaseapp.com',
    storageBucket: 'solnova-50d0e.firebasestorage.app',
    measurementId: 'G-Q1GJ8JZXYX',
  );
}
